sudo: false

language: node_js

script:
  - npm run lint && npm run test

after_script:
  - source ./.travis/report-code-climate.sh

matrix:
  fast_finish: true

  include:
    - os: linux
      node_js: '8'
      before_install:
        - source ./.travis/prepare-linux.sh
        - source ./.travis/prepare-emscripten.sh
        - source ./.travis/setup-code-climate.sh

    - os: linux
      node_js: '10'
      before_install:
        - source ./.travis/prepare-linux.sh
        - source ./.travis/prepare-emscripten.sh
        - source ./.travis/setup-code-climate.sh
